# Generated by Django 5.2.4 on 2025-08-06 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='transacao',
            table='movimentacoes',
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transacoes.categoria'),
        ),
    ]
