# Generated by Django 5.2.2 on 2025-09-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0002_categoria_transacao_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='transacoes.categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='titulo',
            field=models.CharField(db_column='descricao', max_length=100),
        ),
    ]
